WebApp_LMIGREATICE/Models/systemUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class systemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public systemUser()
        {
            this.enteredDatas = new HashSet<enteredData>();
        }

        public int idSystemUser { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("[A-Z]+", ErrorMessage = "Must be written in capital letters. It can not contain numbers, spaces or special characters")]
        [MaxLength(20, ErrorMessage = "Must be between 1 and 20 characters")]
        [DisplayName("First Name")]
        public string firstName { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("[A-Z]+", ErrorMessage = "Must be written in capital letters. It can not contain numbers, spaces or special characters")]
        [MaxLength(20, ErrorMessage = "Must be between 1 and 20 characters")]
        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [EmailAddress(ErrorMessage = "Not a valid Email")]
        [MaxLength(50)]
        [DisplayName("Email")]
        public string email { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [RegularExpression("^.*(?=.{6,64})[a-zA-Z0-9]+$", ErrorMessage = "Password must be between 6 and 64 characters. It can contain only letters and numbers.")]
        public string passwordU { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Gender")]
        public int idGender { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Title")]
        public int idTitle { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime dateOfBirth { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Country")]
        public int idCountry { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Institution")]
        public int idInstitution { get; set; }

        [DisplayName("Privilege")]
        public int idUserPrivilege { get; set; }

        [DisplayName("State")]
        public int idUserState { get; set; }

        public virtual country country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enteredData> enteredDatas { get; set; }
        public virtual gender gender { get; set; }
        public virtual institution institution { get; set; }
        public virtual title title { get; set; }
        public virtual userPrivilege userPrivilege { get; set; }
        public virtual userState userState { get; set; }
    }
}

WebApp_LMIGREATICE/Controllers/systemUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp_LMIGREATICE.Models; //Espacio de nombres que permitirá acceder a los modelos creados por EF a partir de la BBDD
using System.Net; // Permite acceder al tipo Enum HttpStatusCode que es utilizado en la acción "Details"
using System.Security.Cryptography; //Permitirá utilizar SHA-256 para generar la función hash del password e insertarlo en la BBDD
using System.Text; //Permitirá utilizar Encoding para generar la función Hash del password 
using System.Net.Mail; // Permitirá enviar el correo de creación de usuario para confirmación al administrador.

namespace WebApp_LMIGREATICE.Controllers
{
    public class systemUsersController : Controller
    {
        DB_LMIGREATICEEntities1 db = new DB_LMIGREATICEEntities1();

        private static MailAddress origen = new MailAddress("lmigreatice@gmail.com", "LMI GREAT ICE", System.Text.Encoding.UTF8);

        MailMessage correo = new MailMessage()
        {
            From = origen,
        };

        SmtpClient protocolo = new SmtpClient()
        {
            Credentials = new NetworkCredential("lmigreatice@gmail.com", "lgreate4228MI"),
            Port = 587,
            Host = "smtp.gmail.com",
            EnableSsl = true
        };

        // GET: systemUsers
        public ActionResult Index()
        {
            var systemUsers = db.systemUsers.ToList();
            return View(systemUsers);
        }

        // GET: systemUsers/Details/5
        public ActionResult Details(int? id)
        {
            Session["message"] = null;
            Session["notification"] = null;
            Session["error"] = null;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            systemUser user = db.systemUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: systemUsers/Create
        public ActionResult Create()
        {
            ViewBag.genders = new SelectList(db.genders, "idGender", "nameGender");
            ViewBag.titles = new SelectList(db.titles, "idTitle", "nameTitle");
            ViewBag.countries = new SelectList(db.countries, "idCountry", "nameCountry");
            ViewBag.institutions = new SelectList(db.institutions, "idInstitution", "nameInstitution");
            ViewBag.userStates = new SelectList(db.userStates, "idUserState", "nameState");
            ViewBag.userPrivileges = new SelectList(db.userPrivileges, "idUserPrivilege", "namePrivilege");
            return View();
        }

        // POST: systemUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(systemUser userRegister)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = db.systemUsers.Where(a => a.email.Equals(userRegister.email)).FirstOrDefault();
                    if (user == null) //Si no existe usuario con el correo indicado, se crea el usuario.
                    {
                            if (Session["activeSession"] != null && Session["activeSession"].ToString() != "" && (bool)Session["activeSession"] == true)
                            {
                                sendEmailForConfirmation(userRegister);
                                //userRegister.idUserPrivilege = 3; //seteo temporalmente los permisos para download al usuario hasta que se confirme, porque la bbdd no permite nulos
                                // userRegister.idUserState = 3; //seteo el valor de 3 (PENDING), porque la bbdd no admite nulos                                            
                                userRegister.passwordU = ComputeHash256(userRegister.passwordU);
                                db.systemUsers.Add(userRegister);
                                db.SaveChanges();

                                Session.Add("message", "User added successfully");
                                Session["error"] = null;
                                Session["notification"] = null;
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                sendEmailForConfirmation(userRegister);
                                userRegister.idUserPrivilege = 3; //seteo temporalmente los permisos para download al usuario hasta que se confirme, porque la bbdd no permite nulos
                                userRegister.idUserState = 3; //seteo el valor de 3 (PENDING), porque la bbdd no admite nulos                                            
                                userRegister.passwordU = ComputeHash256(userRegister.passwordU);
                                db.systemUsers.Add(userRegister);
                                db.SaveChanges();

                                Session.Add("message", "Your account has been created, however it must be activated by the system Administrator. Meanwhile you will not be able to login. Please wait for an approval");
                                Session["error"] = null;
                                Session["notification"] = null;
                                return RedirectToAction("Create");
                            }
                   
                    }
                    else
                    {
                        Session.Add("error", "User already exists!");
                        Session["message"] = null;
                        Session["notification"] = null;
                        return RedirectToAction("Create");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                Session.Add("error", ex.ToString());
                Session["message"] = null;
                Session["notification"] = null;
                return RedirectToAction("Create");
            }
        }

        // GET: systemUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.systemUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.genders = new SelectList(db.genders, "idGender", "nameGender", "1");
            ViewBag.titles = new SelectList(db.titles, "idTitle", "nameTitle", "1");
            ViewBag.countries = new SelectList(db.countries, "idCountry", "nameCountry", "1");
            ViewBag.institutions = new SelectList(db.institutions, "idInstitution", "nameInstitution", "1");
            ViewBag.privileges = new SelectList(db.userPrivileges, "idUserPrivilege", "namePrivilege", "1");
            ViewBag.states = new SelectList(db.userStates, "idUserState", "nameState", "1");
            return View(user);
        }

        // POST: systemUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Edit(FormCollection collection, int id, systemUser u)
        {
            try
            {                
                // TODO: Add update logic here
                systemUser user = db.systemUsers.Single(i => i.idSystemUser == id);

                if (db.systemUsers.Where(i => i.email == u.email && i.idSystemUser != u.idSystemUser
               && i.idUserState == 1).FirstOrDefault() == null)
                {
                    int aux2 = user.idUserState;

                    user.firstName = u.firstName;
                    user.lastName = u.lastName;
                    user.email = u.email;

                    var aux = db.systemUsers.Where(a => a.idSystemUser.Equals(u.idSystemUser)).FirstOrDefault();

                    if (aux.passwordU == u.passwordU)
                    {
                        user.passwordU = aux.passwordU;
                    }
                    else
                    {
                        user.passwordU = ComputeHash256(u.passwordU);
                    }
                    user.idGender = u.idGender;
                    user.idTitle = u.idTitle;
                    user.idCountry = u.idCountry;
                    user.dateOfBirth = u.dateOfBirth;
                    user.idInstitution = u.idInstitution;

                    if (((int)Session["idUserPrivilege"]) == 1) //Se edita el usuario incluyendo los permisos y el estado
                    {
                        user.idUserPrivilege = u.idUserPrivilege;
                        user.idUserState = u.idUserState;
                        //UpdateModel(user);
                        db.SaveChanges();

                        if (aux2 == 3 && u.idUserState == 1) //Envío correo al usuario indicando que su cuenta ya se activó
                        {
                            sendEmailForChangeState(user);
                        }

                        Session.Add("message", "User updated successfully");
                        Session["error"] = null;
                        Session["notification"] = null;
                        return RedirectToAction("Index");
                    }
                    else //Se edita el usuario sin incluir los permisos y el estado puesto que no tienen autorización
                    {
                        //user.idUserPrivilege = u.idUserPrivilege;
                        //user.idUserState = u.idUserState;
                        //UpdateModel(user);
                        db.SaveChanges();
                        Session.Add("message", "User updated successfully");
                        Session["error"] = null;

WebApp_LMIGREATICE/Views/systemUsers/Create.cshtml
@model WebApp_LMIGREATICE.Models.systemUser

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Add new user</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.passwordU, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.passwordU, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.passwordU, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idGender, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (ViewBag.genders != null)
                    {
                        @Html.DropDownListFor(model => model.idGender, ViewBag.genders as SelectList, "--Select Gender--", htmlAttributes: new { @class = "form-control" })
                    }
                    @Html.ValidationMessageFor(model => model.idGender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.idTitle, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (ViewBag.titles != null)
                    {
                        @Html.DropDownListFor(model => model.idTitle, ViewBag.titles as SelectList, "--Select Title--", htmlAttributes: new { @class = "form-control" })
                    }
                    @Html.ValidationMessageFor(model => model.idTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.dateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.dateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idCountry, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (ViewBag.countries != null)
                    {
                        @Html.DropDownListFor(model => model.idCountry, ViewBag.countries as SelectList, "--Select Country--", htmlAttributes: new { @class = "form-control" })
                    }
                    @Html.ValidationMessageFor(model => model.idCountry, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idInstitution, "Institution", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (ViewBag.institutions != null)
                    {
                        @Html.DropDownListFor(model => model.idInstitution, ViewBag.institutions as SelectList, "--Select Institution--", htmlAttributes: new { @class = "form-control" })
                    }
                    @Html.ValidationMessageFor(model => model.idInstitution, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    @if (Session["idUserPrivilege"] != null && Session["idUserPrivilege"].ToString() != "")
    {
        if ((int)Session["idUserPrivilege"] == 1)
        {
            <div class="form-group">
                    @Html.LabelFor(model => model.idUserPrivilege, "Privilege", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idUserPrivilege, ViewBag.userPrivileges as SelectList, "--Select Privilege--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idUserPrivilege, "", new { @class = "text-danger" })
                    </div>
                </div>

            <div class="form-group">
                    @Html.LabelFor(model => model.idUserState, "State", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idUserState, ViewBag.userStates as SelectList, "--Select State--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idUserState, "", new { @class = "text-danger" })
                    </div>
                </div>
        }
    }


    <div class="form-group text-center">
        <div class="col-md-12 col-md-12">
            <input type="submit" value="Add" class="btn btn-default wine-button" />
            @if (Session["activeSession"] != null && Session["activeSession"].ToString() != "")
            {
                if ((bool)Session["activeSession"] == true)
                {
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default wine-border-button" })
                }
                else
                {
                    @Html.ActionLink("Go to Login", "Login", null, new { @class = "btn btn-default wine-border-button" })
                }
            }
            else
            {
                @Html.ActionLink("Go to Login", "Login", null, new { @class = "btn btn-default wine-border-button" })
            }

        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/systemUsers/Details.cshtml
@model WebApp_LMIGREATICE.Models.systemUser

@{
    ViewBag.Title = "Details";
}

<h2 class="text-center">User details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.passwordU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passwordU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.country.nameCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.country.nameCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender.nameGender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender.nameGender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.institution.nameInstitution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.institution.nameInstitution)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title.nameTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title.nameTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userPrivilege.namePrivilege)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userPrivilege.namePrivilege)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userState.nameState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userState.nameState)
        </dd>

    </dl>
</div>
<p class="text-center">
    @Html.ActionLink("Edit", "Edit", new { id = Model.idSystemUser }, new { @class = "btn btn-default wine-button" })
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-default wine-border-button" })
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/systemUsers/Index.cshtml
@model IEnumerable<WebApp_LMIGREATICE.Models.systemUser>
@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">List of users</h2>
<p>
    @Html.ActionLink("Add user", "Create", "systemUsers", new { @class = "btn btn-default wine-button" })
</p>
<table class="table">
    <thead class="head-table">
        <tr>
            <th>@Html.DisplayName("Name")</th>
            <th>@Html.DisplayNameFor(model => model.email)</th>
            <th>@Html.DisplayNameFor(model => model.country.nameCountry)</th>
            <th>@Html.DisplayNameFor(model => model.institution.nameInstitution)</th>
            <th>@Html.DisplayNameFor(model => model.idUserPrivilege)</th>
            <th>@Html.DisplayNameFor(model => model.idUserState)</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var systemUser in Model)
        {
            <tr>
                <td>@Html.ActionLink(systemUser.firstName + " " + systemUser.lastName, "Edit", new { id = systemUser.idSystemUser }, new { @class = "a-wine" })</td>
                <td>@Html.DisplayFor(x => systemUser.email)</td>
                <td>@Html.DisplayFor(x => systemUser.country.nameCountry)</td>
                <td>@Html.DisplayFor(x => systemUser.institution.nameInstitution)</td>
                <td>@Html.DisplayFor(x => systemUser.userPrivilege.namePrivilege)</td>
                <td>@Html.DisplayFor(x => systemUser.userState.nameState)</td>
                <td>
                    <a href="@Url.Action("Delete", "systemUsers",new { id = systemUser.idSystemUser})" onclick="return confirm('Are you sure you want to delete this?');"><img src="@Url.Content("~/Content/images/trash.png")" style="width:20px;height:auto;"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/systemUsers/Login.cshtml
@model WebApp_LMIGREATICE.Models.systemUser

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Banner_Layout.cshtml";
}

<h2 class="text-center">Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal center">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passwordU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.passwordU, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.passwordU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default wine-button" />
                @Html.ActionLink("Forgot Password?", "passwordRecovery", null, new { @class = "btn btn-default wine-border-button" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/systemUsers/passwordRecovery.cshtml
@model WebApp_LMIGREATICE.Models.systemUser

@{
    ViewBag.Title = "Password recovery";
    Layout = "~/Views/Shared/_Banner_Layout.cshtml";
}

<h2 class="text-center">Reset Password</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Send" class="btn btn-default wine-button" />
            @Html.ActionLink("Return to login", "Login",null,new { @class= "btn btn-default wine-border-button" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}