WebApp_LMIGREATICE/Controllers/AsynController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp_LMIGREATICE.Models;
using WebApp_LMIGREATICE.Models.Extension;
using Hangfire;
using WebApp_LMIGREATICE.Controllers;
using System.Globalization;

namespace WebApp_LMIGREATICE.Controllers
{
    public class AsynController : Controller
    {
        DB_LMIGREATICEEntities1 db = new DB_LMIGREATICEEntities1();

        public ActionResult UploadFile()
        {
            ViewBag.dataTypes = new SelectList(db.dataTypes, "idDataType", "nameDataType", "1");
            ViewBag.measurementTypes = new SelectList(db.measurementTypes, "idMeasurementType", "nameMT");
            //ViewBag.stations = new SelectList(db.stations, "idStation", "nameStation", "1");
            ViewBag.users = new SelectList(db.systemUsers, "idSystemUser", "firstName", "1");
            //Session["error"] = null;
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase fileToCheck, enteredData enteredData) //HttpPostedFileBase FileUpload
        {
            if (Request != null)//control generico de existencia de archivo, que se ha seleccionado el archivo
            {
                //HttpPostedFileBase file = Request.Files["files"]; //leo el archivo subido por el usuario. Elnombre debe coincidir con el declarado en el la Vista
                try
                {
                    if (fileToCheck.ContentLength > 0) //TAMAÑO DEL ARCHIVO MAYOR A 0 BYTES
                    {
                        if (validateFileExtension(fileToCheck)) //extension csv
                        {
                           var fileName = Path.GetFileName(fileToCheck.FileName);
                           var docAux = db.enteredDatas.Where(a => a.nameEnteredData.Equals(fileName)).FirstOrDefault();

                            if (docAux == null) //si no existe un archivo en la bbdd con el mismo nombre, continúo subiendo
                            {
                                StreamReader csvReader = new StreamReader(fileToCheck.InputStream);
                                Holder hold = validateFileStructure(csvReader, enteredData); //validación de estructura de archivo
                                if (hold.status == true)
                                {
                                    int idUser = int.Parse(Session["idSystemUser"].ToString());
                                    var path = Path.Combine(Server.MapPath("~/UploadedFiles/TemporaryFiles"), fileName);
                                    fileToCheck.SaveAs(path);
                                    string finalName = "ORIGINAL-" + fileName;//Path.GetFileName(fileToCheck.FileName);
                                    string finalPath = Path.Combine(Server.MapPath("~/UploadedFiles"), finalName);
                                    BackgroundJob.Enqueue(() => saveFileData(fileName, path, finalPath, enteredData, idUser ));//, System.Web.HttpContext.Current));
                                    Session.Add("message", "Upload process started. DO NOT close the website until this process finished!");
                                    Session["error"] = null;
                                    Session["notification"] = null;
                                }
                                else
                                {
                                    Session["error"] = hold.message;
                                    Session["message"] = null;
                                    Session["notification"] = null;
                                    return RedirectToAction("UploadFile");
                                }
                            }
                            else
                            {
                                Session["error"] = "It seems that someone has already upload a file with the same name. Please verify it!";
                                Session["message"] = null;
                                Session["notification"] = null;
                                return RedirectToAction("UploadFile");
                            }                            
                        }
                        else
                        {
                            Session["error"] = "The file must have an extension .csv";
                            Session["message"] = null;
                            Session["notification"] = null;
                        }
                        return RedirectToAction("UploadFile");
                    }
                }
                catch(Exception ex)
                {
                    Session["error"] = ex.Message + "\nFile upload failed!" + " " + "Please verify that there are no NULL fields";
                    Session["message"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("UploadFile");
                }
            }
            return RedirectToAction("UploadFile");
        }

        public void saveFileData(string nameOfFile,string path, string finalPath,enteredData enteredData, int idUser)//, HttpContext mainContext)
        {
            //await Task.Run(() => {
            using (var csvReader = new StreamReader(path)) {
                csvReader.BaseStream.Seek(0, SeekOrigin.Begin); //Resetea la posición del stream para que empiece de nuevo
                
                //Insertar Datos en la BBDD
                int rowNumber = 1;
                int idDocument = checkAndInsertDocumentFeatures(idUser, enteredData, nameOfFile);//Path.GetFileName(fileToCheck.FileName));
                var selectedStation = db.stations.Where(a => a.idStation.Equals(enteredData.idStation)).FirstOrDefault();
                //{
                while (!csvReader.EndOfStream)
                {
                    
                    if (selectedStation.measurementType.nameMT == "Meteorological")
                    {
                        string reader = csvReader.ReadLine();
                        if (!reader.Contains("#"))
                        {
                            //Session["message"] = null;
                           // Session["notification"] = "Loading data...";
                           // Session["error"] = null;
                            bool respHeaders = insertMeteorologicalData(idDocument, reader, selectedStation);                           
                        }
                        else
                        {
                            //Session["message"] = null;
                           // Session["notification"] = "Loading data...";
                           // Session["error"] = null;
                            bool respMetData = insertMeteoMetadata(idDocument, rowNumber, reader, enteredData);
                            rowNumber = rowNumber + 1;
                        }
                    }
                    else if (selectedStation.measurementType.nameMT == "Glaciological")
                    {
                        string reader = csvReader.ReadLine();
                        if (!reader.Contains("#"))
                        {
                            //Session["message"] = null;
                            //Session["notification"] = "Loading data...";
                            //Session["error"] = null;
                            bool respGlaData = insertGlaciologicalData(idDocument, reader);
                        }
                    }
                    else
                    {
                        //Session["message"] = null;
                        //Session["notification"] = "Loading data...";
                        //Session["error"] = null;
                        string reader = csvReader.ReadLine();
                        bool respHydrData = insertHydrologicalData(idDocument, rowNumber, reader);
                        rowNumber = rowNumber + 1;
                    }
                }
                try
                {
                    System.IO.File.Copy(path, finalPath);
                    //FinalizarCarga("Upload data process has finished", null, null,mainContext);
                    Session.Add("message", "Upload data process has finished");
                    Session["notification"] = null;
                    Session["error"] = null;
                    var name = Url.Action();
                    RedirectToAction(name);
                }
                catch (Exception ex) {
                    //FinalizarCarga(null, null, ex.Message, mainContext);
                }                                        
            }   
           // });
            //return await Task.FromResult(true);
        }

        public void FinalizarCarga(string message, string notif, string error, HttpContext context)
        {
            context.Session.Add("message", message);
            context.Session["notification"] = notif;
            context.Session["error"] = error;
            var name = Url.Action();
            RedirectToRoute(name);
            //directToAction(name);
        }

        public bool validateFileExtension(HttpPostedFileBase fileToCheck) //VALIDA QUE EL ARCHIVO A SUBIR TENGA EXTENSION .csv
        {
            try
            {
                var supportedTypes = new[] { "csv" };
                var fileExtension = Path.GetExtension(fileToCheck.FileName).Substring(1);
                return (!supportedTypes.Contains(fileExtension) ? false : true);
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        public Holder validateFileStructure(StreamReader csvReader, enteredData enteredData) //VALIDA ESTRUCTURA A TRAVÉS DE LA CLASE StructureValidation
        {
            Holder hold = new Holder();
            var selectedStation = db.stations.Where(a => a.idStation.Equals(enteredData.idStation)).FirstOrDefault();

WebApp_LMIGREATICE/Views/Asyn/UploadFile.cshtml
@model WebApp_LMIGREATICE.Models.enteredData

@{
    ViewBag.Title = "UploadFile";
}
<h2 class="text-center">Upload a CSV file</h2>

@using (Html.BeginForm("UploadFile", "Asyn", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <hr />
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.idDataType, "Data Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idDataType, ViewBag.dataTypes as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idDataType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.station.idMeasurementType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("idMeasurementType", ViewBag.measurementTypes as SelectList, "Select a measurment type", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.station.measurementType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Station", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idStation, new SelectList(""), "--Select Station--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessage("", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="text-center">
                    <input type="file" name="fileToCheck" class="btn btn-default wine-button" style="background-color:#000" /><br /> <br />
                    <input type="submit" value="Upload" class="btn btn-default wine-button" />


                    @if (Session["idUserPrivilege"] != null && Session["idUserPrivilege"].ToString() != "")
                    {
                        if (((int)Session["idUserPrivilege"]) == 1)
                        {
                            @Html.ActionLink("Back to List", "Index", "enteredData", null, new { @class = "btn btn-default wine-border-button" })
                        }
                    }
                    @*@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default wine-border-button" })*@
                </div><br />
                <p>
                    <b>
                        Note: Depending of the measurement types, there are many formats that the documents must comply to be uploaded to the system. If the
                        documents do not comply the specified format, they will not be uploaded.  Also, the documents must have at least one row of records.
                        For checking the specified formats please visit
                        <a href="https://drive.google.com/open?id=1bKhymD_l8851kRN9lcUpPfzLkKjmWiLQ">this link</a>
                    </b>
                </p>
                
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#idMeasurementType').on('change', function () {
                // alert($("#idMeasurementType").val());
                $.get("/enteredData/GetStationList", { idMType: $("#idMeasurementType").val() }, function (data) {
                    $("#idStation").empty();
                    $.each(data, function (index, row) {
                        $("#idStation").append("<option value='" + row.idStation + "'>" + row.nameStation + "</option>")
                    });
                });
            })
        });
    </script>
}