WebApp_LMIGREATICE/Controllers/stationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net; // Permite acceder al tipo Enum HttpStatusCode que es utilizado en la acción "Details"
using WebApp_LMIGREATICE.Models; //Espacio de nombres que permitirá acceder a los modelos creados por EF a partir de la BBDD

namespace WebApp_LMIGREATICE.Controllers
{
    public class stationsController : Controller
    {
        DB_LMIGREATICEEntities1 db = new DB_LMIGREATICEEntities1();

        // GET: stations
        public ActionResult Index()
        {
            var stations = db.stations.OrderByDescending(i => i.stateR).ThenBy(i => i.nameStation).ToList();
            return View(stations);
        }

        // GET: stations/Details/5
        public ActionResult Details(int? id)
        {
            Session["error"] = null;
            Session["notification"] = null;
            Session["message"] = null;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            station station = db.stations.Single(i => i.idStation == id);
            if (station == null)
            {
                return HttpNotFound();
            }
            return View(station);
        }

        // GET: stations/Create
        public ActionResult Create()
        {
            ViewBag.locations = new SelectList(db.locations.ToList(), "idLocation", "nameLocation");
            ViewBag.glaciers = new SelectList(db.glaciers.Where(i => i.stateR ==true).ToList(), "idGlacier", "nameGlacier");
            ViewBag.measurementTypes = new SelectList(db.measurementTypes.ToList(), "idMeasurementType", "nameMT");
            return View();
        }

        // POST: stations/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, station station)
        {
            try
            {
                var newStation = db.stations.Where(a => a.nameStation.Equals(station.nameStation)).FirstOrDefault();
                if (newStation == null)
                {
                    db.stations.Add(station);
                    db.SaveChanges();
                    Session.Add("message", "Station added successfully");
                    Session["error"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Index");
                }
                else
                {
                    Session.Add("error", "This station already exists!");
                    Session["message"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Create");
                }
            }
            catch(Exception ex)
            {
                Session["error"] = ex.Message;
                return View();
            }
        }

        // GET: stations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //var station = db.glaciers.Single(i => i.idGlacier == id);
            var station = db.stations.Single(i => i.idStation == id);
            if (station == null)
            {
                return HttpNotFound();
            }
            ViewBag.locations = new SelectList(db.locations.ToList(), "idLocation", "nameLocation");
            ViewBag.glaciers = new SelectList(db.glaciers.ToList(), "idGlacier", "nameGlacier");
            ViewBag.measurementTypes = new SelectList(db.measurementTypes.ToList(), "idMeasurementType", "nameMT");
            return View(station);
        }

        // POST: stations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Edit(int id, FormCollection collection, station newStation)
        {
            try
            {
                station station = db.stations.Single(i => i.idStation == id);
                if (db.stations.Where(i => i.nameStation == newStation.nameStation && i.idStation != newStation.idStation
                && i.stateR == true).FirstOrDefault() == null)
                {
                    UpdateModel(station);
                    db.SaveChanges();
                    Session.Add("message", "Station updated successfully");
                    Session["error"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Index");
                }
                else
                {
                    Session.Add("error", "A station with the same name alreaddy exists!");
                    Session["message"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Edit", id);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: stations/Delete/5
        public ActionResult Delete(int id)
        {
            station station = db.stations.Single(i => i.idStation == id);
            station.stateR = false;
            db.SaveChanges();
            Session.Add("message", "Station desactivated successfully");
            Session["error"] = null;
            Session["notification"] = null;
            return RedirectToAction("Index");
        }

        // POST: stations/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp_LMIGREATICE/Controllers/systemUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp_LMIGREATICE.Models; //Espacio de nombres que permitirá acceder a los modelos creados por EF a partir de la BBDD
using System.Net; // Permite acceder al tipo Enum HttpStatusCode que es utilizado en la acción "Details"
using System.Security.Cryptography; //Permitirá utilizar SHA-256 para generar la función hash del password e insertarlo en la BBDD
using System.Text; //Permitirá utilizar Encoding para generar la función Hash del password 
using System.Net.Mail; // Permitirá enviar el correo de creación de usuario para confirmación al administrador.

namespace WebApp_LMIGREATICE.Controllers
{
    public class systemUsersController : Controller
    {
        DB_LMIGREATICEEntities1 db = new DB_LMIGREATICEEntities1();

        private static MailAddress origen = new MailAddress("lmigreatice@gmail.com", "LMI GREAT ICE", System.Text.Encoding.UTF8);

        MailMessage correo = new MailMessage()
        {
            From = origen,
        };

        SmtpClient protocolo = new SmtpClient()
        {
            Credentials = new NetworkCredential("lmigreatice@gmail.com", "lgreate4228MI"),
            Port = 587,
            Host = "smtp.gmail.com",
            EnableSsl = true
        };

        // GET: systemUsers
        public ActionResult Index()
        {
            var systemUsers = db.systemUsers.ToList();
            return View(systemUsers);
        }

        // GET: systemUsers/Details/5
        public ActionResult Details(int? id)
        {
            Session["message"] = null;
            Session["notification"] = null;
            Session["error"] = null;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            systemUser user = db.systemUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: systemUsers/Create
        public ActionResult Create()
        {
            ViewBag.genders = new SelectList(db.genders, "idGender", "nameGender");
            ViewBag.titles = new SelectList(db.titles, "idTitle", "nameTitle");
            ViewBag.countries = new SelectList(db.countries, "idCountry", "nameCountry");
            ViewBag.institutions = new SelectList(db.institutions, "idInstitution", "nameInstitution");
            ViewBag.userStates = new SelectList(db.userStates, "idUserState", "nameState");
            ViewBag.userPrivileges = new SelectList(db.userPrivileges, "idUserPrivilege", "namePrivilege");
            return View();
        }

        // POST: systemUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(systemUser userRegister)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = db.systemUsers.Where(a => a.email.Equals(userRegister.email)).FirstOrDefault();
                    if (user == null) //Si no existe usuario con el correo indicado, se crea el usuario.
                    {
                            if (Session["activeSession"] != null && Session["activeSession"].ToString() != "" && (bool)Session["activeSession"] == true)
                            {
                                sendEmailForConfirmation(userRegister);
                                //userRegister.idUserPrivilege = 3; //seteo temporalmente los permisos para download al usuario hasta que se confirme, porque la bbdd no permite nulos
                                // userRegister.idUserState = 3; //seteo el valor de 3 (PENDING), porque la bbdd no admite nulos                                            
                                userRegister.passwordU = ComputeHash256(userRegister.passwordU);
                                db.systemUsers.Add(userRegister);
                                db.SaveChanges();

                                Session.Add("message", "User added successfully");
                                Session["error"] = null;
                                Session["notification"] = null;
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                sendEmailForConfirmation(userRegister);
                                userRegister.idUserPrivilege = 3; //seteo temporalmente los permisos para download al usuario hasta que se confirme, porque la bbdd no permite nulos
                                userRegister.idUserState = 3; //seteo el valor de 3 (PENDING), porque la bbdd no admite nulos                                            
                                userRegister.passwordU = ComputeHash256(userRegister.passwordU);
                                db.systemUsers.Add(userRegister);
                                db.SaveChanges();

                                Session.Add("message", "Your account has been created, however it must be activated by the system Administrator. Meanwhile you will not be able to login. Please wait for an approval");
                                Session["error"] = null;
                                Session["notification"] = null;
                                return RedirectToAction("Create");
                            }
                   
                    }
                    else
                    {
                        Session.Add("error", "User already exists!");
                        Session["message"] = null;
                        Session["notification"] = null;
                        return RedirectToAction("Create");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                Session.Add("error", ex.ToString());
                Session["message"] = null;
                Session["notification"] = null;
                return RedirectToAction("Create");
            }
        }

        // GET: systemUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.systemUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.genders = new SelectList(db.genders, "idGender", "nameGender", "1");
            ViewBag.titles = new SelectList(db.titles, "idTitle", "nameTitle", "1");
            ViewBag.countries = new SelectList(db.countries, "idCountry", "nameCountry", "1");
            ViewBag.institutions = new SelectList(db.institutions, "idInstitution", "nameInstitution", "1");
            ViewBag.privileges = new SelectList(db.userPrivileges, "idUserPrivilege", "namePrivilege", "1");
            ViewBag.states = new SelectList(db.userStates, "idUserState", "nameState", "1");
            return View(user);
        }

        // POST: systemUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Edit(FormCollection collection, int id, systemUser u)
        {
            try
            {                
                // TODO: Add update logic here
                systemUser user = db.systemUsers.Single(i => i.idSystemUser == id);

                if (db.systemUsers.Where(i => i.email == u.email && i.idSystemUser != u.idSystemUser
               && i.idUserState == 1).FirstOrDefault() == null)
                {
                    int aux2 = user.idUserState;

                    user.firstName = u.firstName;
                    user.lastName = u.lastName;
                    user.email = u.email;

                    var aux = db.systemUsers.Where(a => a.idSystemUser.Equals(u.idSystemUser)).FirstOrDefault();

                    if (aux.passwordU == u.passwordU)
                    {
                        user.passwordU = aux.passwordU;
                    }
                    else
                    {
                        user.passwordU = ComputeHash256(u.passwordU);
                    }
                    user.idGender = u.idGender;
                    user.idTitle = u.idTitle;
                    user.idCountry = u.idCountry;
                    user.dateOfBirth = u.dateOfBirth;
                    user.idInstitution = u.idInstitution;

                    if (((int)Session["idUserPrivilege"]) == 1) //Se edita el usuario incluyendo los permisos y el estado
                    {
                        user.idUserPrivilege = u.idUserPrivilege;
                        user.idUserState = u.idUserState;
                        //UpdateModel(user);
                        db.SaveChanges();

                        if (aux2 == 3 && u.idUserState == 1) //Envío correo al usuario indicando que su cuenta ya se activó
                        {
                            sendEmailForChangeState(user);
                        }

                        Session.Add("message", "User updated successfully");
                        Session["error"] = null;
                        Session["notification"] = null;
                        return RedirectToAction("Index");
                    }
                    else //Se edita el usuario sin incluir los permisos y el estado puesto que no tienen autorización
                    {
                        //user.idUserPrivilege = u.idUserPrivilege;
                        //user.idUserState = u.idUserState;
                        //UpdateModel(user);
                        db.SaveChanges();
                        Session.Add("message", "User updated successfully");
                        Session["error"] = null;

WebApp_LMIGREATICE/Views/systemUsers/stations/Create.cshtml
@model WebApp_LMIGREATICE.Models.station

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Add new station</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.nameStation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nameStation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nameStation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.latitudeStation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.latitudeStation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.latitudeStation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.longitudeStation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.longitudeStation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.longitudeStation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.altitudeStation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.altitudeStation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.altitudeStation, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.idGlacier, "Glacier", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idGlacier, ViewBag.glaciers as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idGlacier, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.idLocation, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idLocation, ViewBag.locations as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idLocation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.idMeasurementType, "Measurement Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.idMeasurementType, ViewBag.measurementTypes as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idMeasurementType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.stateR, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.stateR)
                            @Html.ValidationMessageFor(model => model.stateR, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group text-center">
            <div class="col-md-12 col-md-12">
                <input type="submit" value="Add" class="btn btn-default wine-button" />
                @Html.ActionLink("Back to List", "Index",null, new { @class= "btn btn-default wine-border-button" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/systemUsers/stations/Edit.cshtml
@model WebApp_LMIGREATICE.Models.station

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Station edition</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idStation)
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.nameStation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nameStation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nameStation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.latitudeStation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.latitudeStation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.latitudeStation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.longitudeStation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.longitudeStation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.longitudeStation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.altitudeStation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.altitudeStation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.altitudeStation, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.idGlacier, "Glacier", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.idGlacier, ViewBag.glaciers as SelectList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idGlacier, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idLocation, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.idLocation, ViewBag.locations as SelectList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idLocation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idMeasurementType, "Measurement Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.idMeasurementType, ViewBag.measurementTypes as SelectList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idMeasurementType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.stateR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.stateR)
                        @Html.ValidationMessageFor(model => model.stateR, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />

    <div class="form-group text-center">
        <div class="col-md-12 col-md-12">
            <input type="submit" value="Save" class="btn btn-default wine-button" />
            @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-default wine-border-button" })
        </div>
    </div>
</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/systemUsers/stations/Index.cshtml
@model IEnumerable<WebApp_LMIGREATICE.Models.station>
@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">List of stations</h2>
<p>
    @Html.ActionLink("Add station", "Create", "stations", new { @class = "btn btn-default wine-button" })
</p>

<table class="table">
    <thead class="head-table">
        <tr>
            @*<th>@Html.DisplayNameFor(model => model.idStation)</th>*@
            <th>@Html.DisplayNameFor(model => model.nameStation)</th>
            <th>@Html.DisplayNameFor(model => model.latitudeStation)</th>
            <th>@Html.DisplayNameFor(model => model.longitudeStation)</th>
            <th>@Html.DisplayNameFor(model => model.altitudeStation)</th>
            <th>@Html.DisplayNameFor(model => model.idGlacier)</th>
            <th>@Html.DisplayNameFor(model => model.idLocation)</th>
            <th>@Html.DisplayNameFor(model => model.idMeasurementType)</th>
            <th>@Html.DisplayNameFor(model => model.stateR)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>@Html.DisplayFor(modelItem => item.idStation)</td>*@
                <td>@Html.ActionLink(item.nameStation,"Edit", new { id= item.idStation},new { @class = "a-wine"})</td>
                <td>@Html.DisplayFor(modelItem => item.latitudeStation)</td>
                <td>@Html.DisplayFor(modelItem => item.longitudeStation)</td>
                <td>@Html.DisplayFor(modelItem => item.altitudeStation)</td>
                <td>@Html.DisplayFor(modelItem => item.glacier.nameGlacier)</td>
                <td>@Html.DisplayFor(modelItem => item.location.nameLocation)</td>
                <td>@Html.DisplayFor(modelItem => item.measurementType.nameMT)</td>
                <td>@Html.DisplayFor(modelItem => item.stateR)</td>
                <td>
                    <a href="@Url.Action("Delete", "stations",new { id = item.idStation})" onclick="return confirm('Are you sure you want to delete this?');"><img src="@Url.Content("~/Content/images/trash.png")" style="width:20px;height:auto;"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}