WebApp_LMIGREATICE/Models/mountain.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mountain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mountain()
        {
            this.glaciers = new HashSet<glacier>();
        }

        public int idMountain { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("[A-Z]+", ErrorMessage = "Must be written in capital letters. It can not contain numbers, spaces or special characters")]
        [MaxLength(25, ErrorMessage = "Must be between 1 and 25 characters")]
        [DisplayName("Name Mountain")]
        public string nameMountain { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Country")]
        public int idProjectCountry { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("State")]
        public bool stateR { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<glacier> glaciers { get; set; }
        public virtual projectCountry projectCountry { get; set; }
    }
}

WebApp_LMIGREATICE/Controllers/mountainsController.cs
using System.Linq;
using System.Net; // Permite acceder al tipo Enum HttpStatusCode que es utilizado en la acción "Details"
using System.Web.Mvc;
using WebApp_LMIGREATICE.Models; //Espacio de nombres que permitirá acceder a los modelos creados por EF a partir de la BBDD

namespace WebApp_LMIGREATICE.Controllers
{
    public class mountainsController : Controller
    {
        DB_LMIGREATICEEntities1 db = new DB_LMIGREATICEEntities1(); //La creación de una instancia de la Context Class permitirá 
                                                                  //acceder y manipular la BBDD.
                                                                  
        // GET: mountains
        public ActionResult Index() //Permite leer los datos de la respectiva tabla en la BBDD y enviarlos a la vista Index
        {
                var mountains = db.mountains.OrderByDescending(i => i.stateR).ThenBy(i => i.nameMountain).ToList();
                return View(mountains);
        }

        // GET: mountains/Details/5
        public ActionResult Details(int? id)
        {
            Session["error"] = null;
            Session["message"] = null;
            Session["notification"] = null;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mountain mountain = db.mountains.Find(id);
            if (mountain == null)
            {
                return HttpNotFound();
            }
            return View(mountain);
        }

        // GET: mountains/Create
        public ActionResult Create()
        {
            ViewBag.countries = new SelectList(db.projectCountries.ToList(), "idProjectCountry", "nameCountry");
            return View();
        }

        // POST: mountains/Create
        [HttpPost]
        public ActionResult Create(mountain mountain) //Pasa los datos ingresados por el usuario a la BBDD para insertarlos
        {
            try
            {
                var newMountain = db.mountains.Where(a => a.nameMountain.Equals(mountain.nameMountain)).FirstOrDefault();
                if (newMountain == null)
                {
                    db.mountains.Add(mountain);
                    db.SaveChanges();
                    Session.Add("message", "Mountain added successfully");
                    Session["error"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Index");
                }
                else
                {
                    Session.Add("error", "This mountain already exists!");
                    Session["message"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Create");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: mountains/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var mountain = db.mountains.Find(id);

            if (mountain == null)
            {
                return HttpNotFound();
            }
            ViewBag.countries = new SelectList(db.projectCountries.ToList(), "idProjectCountry", "nameCountry");
            ViewBag.showSuccessAlert=false;
            return View(mountain);
        }

        // POST: mountains/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, mountain newMountain)
        {
            try
            {
                mountain mountain = db.mountains.Single(i => i.idMountain == id);
                if (db.mountains.Where(i => i.nameMountain == newMountain.nameMountain && i.idMountain != newMountain.idMountain
                 && i.stateR == true).FirstOrDefault() == null)
                {
                    UpdateModel(mountain);
                    db.SaveChanges();
                    Session.Add("message", "Mountain updated successfully");
                    Session["error"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Index");
                }
                else
                {
                    Session.Add("error", "A mountain with the same name alreaddy exists!");
                    Session["message"] = null;
                    Session["notification"] = null;
                    return RedirectToAction("Edit", id);
                }
            }
            catch
            {
                Session.Add("error", "Error!");
                Session["message"] = null;
                Session["notification"] = null;
                return View();
            }

        }

        // GET: mountains/Delete/5
        public ActionResult Delete(int id)
        {
            mountain mountain = db.mountains.Single(i => i.idMountain == id);
            mountain.stateR = false;
            db.SaveChanges();
            Session.Add("message", "Mountain desactivated successfully");
            Session["error"] = null;
            Session["notification"] = null;
            return RedirectToAction("Index");          
        }

        // POST: mountains/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp_LMIGREATICE/Views/mountains/Create.cshtml
@model WebApp_LMIGREATICE.Models.mountain

@{
    ViewBag.Title = "Create";
}

<h2  class="text-center">Add new mountain</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>mountain</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nameMountain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nameMountain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nameMountain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idProjectCountry, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idProjectCountry, ViewBag.countries as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idProjectCountry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stateR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.stateR)
                    @Html.ValidationMessageFor(model => model.stateR, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group text-center">
            <div class="col-md-12 col-md-12">
                <input type="submit" value="Add" class="btn btn-default wine-button" />
                @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-default wine-border-button" })
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/mountains/Details.cshtml
@model WebApp_LMIGREATICE.Models.mountain

@{
    ViewBag.Title = "Details";
}

<h2 class="text-center">Mountain details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nameMountain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nameMountain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectCountry.nameCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectCountry.nameCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stateR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stateR)
        </dd>
    </dl>
</div>
<p class="text-center">
    @Html.ActionLink("Edit", "Edit", new { id = Model.idMountain }, new { @class = "btn btn-default wine-button" }) |
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-default wine-border-button" })
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/mountains/Edit.cshtml
@model WebApp_LMIGREATICE.Models.mountain

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center">Mountain edition</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>mountain</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idMountain)

        <div class="form-group">
            @Html.LabelFor(model => model.nameMountain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nameMountain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nameMountain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idProjectCountry, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idProjectCountry, ViewBag.countries as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idProjectCountry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stateR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.stateR)
                    @Html.ValidationMessageFor(model => model.stateR, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group text-center">
            <div class="col-md-12 col-md-12">
                <input type="submit" value="Save" class="btn btn-default wine-button" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default wine-border-button" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp_LMIGREATICE/Views/mountains/Index.cshtml
@model IEnumerable<WebApp_LMIGREATICE.Models.mountain>
@{
    ViewBag.Title = "Index";
}


<h2 class="text-center">List of mountains</h2>
<p>
    @Html.ActionLink("Add mountain", "Create", "mountains", new { @class = "btn btn-default wine-button" })
</p>

<table class="table">
    <thead class="head-table">
        <tr>
            @*<th>@Html.DisplayNameFor(model => model.idMountain)</th>*@
            <th>@Html.DisplayNameFor(model => model.nameMountain)</th>
            <th>@Html.DisplayNameFor(model => model.idProjectCountry)</th>
            <th>@Html.DisplayNameFor(model => model.stateR)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>@Html.DisplayFor(modelItem => item.idMountain)</td>*@
                <td>@Html.ActionLink(item.nameMountain,"Edit", new { id = item.idMountain }, new { @class = "a-wine" })</td>
                <td>@Html.DisplayFor(modelItem => item.projectCountry.nameCountry)</td>
                <td>@Html.DisplayFor(modelItem => item.stateR)</td>
                <td>
                    <a href="@Url.Action("Delete", "mountains",new { id = item.idMountain})" onclick="return confirm('Are you sure you want to delete this?');"><img src="@Url.Content("~/Content/images/trash.png")" style="width:20px;height:auto;"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}